/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication3;

import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class Zalagane extends javax.swing.JFrame {

    private SetGet obj = new SetGet();

    /**
     * Creates new form BlackJack2
     */

    public Zalagane() {
        initComponents();
       
        nachalo obj1 = new nachalo();
        Random rand = new Random();
       
        int sluchaen2 = 0;
        int sluchaen1 = rand.nextInt(21) + 0;
        obj.setOtbor1(obj.getOtbori()[sluchaen1]);
        for (;;) {
            sluchaen2 = rand.nextInt(21) + 0;
            if (sluchaen2 != sluchaen1) {
                obj.setOtbor2(obj.getOtbori()[sluchaen2]);
                break;
            }
        }

        otbor1.setText(obj.getOtbor1());
        otbor2.setText(obj.getOtbor2());
        if (sluchaen1 < 5) {
            koef1.setText("1.35");
            obj.setKoeficient1(2);
            obj.setZalog1(Integer.parseInt(koef1.getText()));
        } else if (sluchaen1 < 10) {
            koef1.setText("1.35");
            obj.setKoeficient1(4);
            obj.setZalog1(Integer.parseInt(koef1.getText()));
        } else if (sluchaen1 < 15) {
            koef1.setText("1.35");
            obj.setKoeficient1(7);
            obj.setZalog1(Integer.parseInt(koef1.getText()));
        } else {
            koef1.setText("2.50");
            obj.setKoeficient1(10);
            obj.setZalog1(Integer.parseInt(koef1.getText()));
        }
        if (sluchaen2 < 5) {
            koef2.setText("1.35");
            obj.setKoeficient2(2);
            obj.setZalog2(Integer.parseInt(koef2.getText()));
        } else if (sluchaen2 < 10) {
            koef2.setText("1.35");
            obj.setKoeficient2(4);
            obj.setZalog2(Integer.parseInt(koef2.getText()));
        } else if (sluchaen2 < 15) {
            koef2.setText("1.35");
            obj.setKoeficient2(7);
            obj.setZalog2(Integer.parseInt(koef2.getText()));
        } else {
            koef2.setText("2.50");
            obj.setKoeficient2(10);
            obj.setZalog2(Integer.parseInt(koef2.getText()));
        }

        koefX.setText("2.85");
        suma.setText(obj1.getSuma() + "лв.");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        otbor1 = new javax.swing.JLabel();
        rezultat = new javax.swing.JLabel();
        otbor2 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        suma = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        zalSuma = new javax.swing.JTextPane();
        buttOtbor1 = new javax.swing.JRadioButton();
        buttOtbor2 = new javax.swing.JRadioButton();
        buttDraw = new javax.swing.JRadioButton();
        koef1 = new javax.swing.JLabel();
        koefX = new javax.swing.JLabel();
        koef2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 600));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(250, 250, 250));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("НеПеМеГе Футбол");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jButton1.setBackground(new java.awt.Color(95, 95, 95));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jButton1.setForeground(new java.awt.Color(250, 250, 250));
        jButton1.setText("← Назад");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(50, 50, 50)));
        jButton1.setFocusPainted(false);
        jButton1.setRolloverEnabled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Започни");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        otbor1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        otbor1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        otbor1.setText("otbor1");

        rezultat.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rezultat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rezultat.setText("-");
        rezultat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        otbor2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        otbor2.setText("otbor2");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setText("Сума в акаунта:");

        suma.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        suma.setText("0");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel3.setText("Заложена сума:");

        jScrollPane1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jScrollPane1.setViewportView(zalSuma);

        buttonGroup1.add(buttOtbor1);
        buttOtbor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttOtbor1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(buttOtbor2);
        buttOtbor2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttOtbor2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(buttDraw);
        buttDraw.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        buttDraw.setText("X");
        buttDraw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttDrawActionPerformed(evt);
            }
        });

        koef1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        koef1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        koefX.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        koefX.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        koef2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        koef2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        koef2.setText(" ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(suma, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(koef1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(156, 156, 156)
                        .addComponent(koefX, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(koef2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(buttOtbor1)
                        .addGap(15, 15, 15)
                        .addComponent(otbor1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(rezultat, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                        .addComponent(otbor2, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttOtbor2)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(312, 312, 312)
                .addComponent(buttDraw)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buttDraw)
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttOtbor1)
                    .addComponent(buttOtbor2)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(otbor1)
                        .addComponent(rezultat)
                        .addComponent(otbor2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(koef1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(koefX, javax.swing.GroupLayout.DEFAULT_SIZE, 17, Short.MAX_VALUE)
                    .addComponent(koef2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(suma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(286, 286, 286))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(264, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(117, 117, 117))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 796, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jPanel1, 573, 573, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
        new nachalo().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Random rand = new Random();
        nachalo obekt = new nachalo();
        Zalagane otbor = new Zalagane();
        int pechelivsh = 0;
        try {
            int zalozhena = Integer.parseInt(zalSuma.getText());

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Въведете валидна сума", "Невалидна сума!", JOptionPane.ERROR_MESSAGE);
            zalSuma.setText(" ");
        }
        int pecheli = 0;

        int koeficientX = (obj.getKoeficient1() + obj.getKoeficient2());
        int golove1 = 0, golove2 = 0;
        int team1 = rand.nextInt(obj.getKoeficient1() * 100) + 1;
        int team2 = rand.nextInt(obj.getKoeficient2() * 100) + 1;
        int teamX = rand.nextInt(koeficientX * 100) + 1;
        if (team1 < team2 && team1 < teamX) {
            pecheli = 1; //1
        } else if (team2 < team1 && team2 < teamX) {
            pecheli = 2; // 2
        } else {
            pecheli = 3;//x
        }
        if (pecheli == 1) {
            golove1 = rand.nextInt(7) + 1;
            golove2 = rand.nextInt(golove1);
            pechelivsh = 1;
        } else if (pecheli == 2) {
            golove2 = rand.nextInt(7) + 1;
            golove1 = rand.nextInt(golove2);
            pechelivsh = 2;
        } else if (pecheli == 3) {
            golove1 = rand.nextInt(5);
            golove2 = golove1;
            pechelivsh = 3;
        }
        String rezultat1 = Integer.toString(golove1) + "-" + Integer.toString(golove2);
        rezultat.setText(rezultat1);
        System.out.println(obj.getIzborotbor());
        int balans = Integer.parseInt(obekt.getSuma());
        int zalozheno = Integer.parseInt(zalSuma.getText());
        float a=0;
        if (obj.getIzborotbor() == pechelivsh && obj.getIzborotbor() == 1) {
         //a =  zalozheno*obj.getZalog1();
         JOptionPane.showMessageDialog(null,"Въведете валидна сума", "Невалидна сума!",JOptionPane.ERROR_MESSAGE);
        }
        else;
    }//GEN-LAST:event_jButton2ActionPerformed

    private void buttOtbor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttOtbor1ActionPerformed

        obj.setIzborotbor(1);
    }//GEN-LAST:event_buttOtbor1ActionPerformed

    private void buttDrawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttDrawActionPerformed
        obj.setIzborotbor(3);
    }//GEN-LAST:event_buttDrawActionPerformed

    private void buttOtbor2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttOtbor2ActionPerformed

        obj.setIzborotbor(2);
    }//GEN-LAST:event_buttOtbor2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Zalagane.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Zalagane.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Zalagane.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Zalagane.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Zalagane().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton buttDraw;
    private javax.swing.JRadioButton buttOtbor1;
    private javax.swing.JRadioButton buttOtbor2;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel koef1;
    private javax.swing.JLabel koef2;
    private javax.swing.JLabel koefX;
    private javax.swing.JLabel otbor1;
    private javax.swing.JLabel otbor2;
    private javax.swing.JLabel rezultat;
    private javax.swing.JLabel suma;
    private javax.swing.JTextPane zalSuma;
    // End of variables declaration//GEN-END:variables
}
